### ISSUE TITLE
Some states are missing their full names (e.g. 'York' should be 'New York')

### ISSUE THREAD

**Issue by cminnich** [alocke12992/Merica#1]
All states with more than 1 word in their name (New Hampshire, New Jersey, New York, New Mexico, North Carolina, North Dakota, Rhode Island, South Carolina, South Dakota and West Virginia) are missing the first word in their name within the fullNames and fullNameToAbbreviation and states.fullName constants ('York': 'NY' -> 'New York': 'NY')

**Comment by alocke12992** [comment]
Closed with v1.0.3
